CREATE RESERVATION(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	USER_ID INT NOT NULL,
	MOVIE_ID INT NOT NULL,
	MOVIE_TIME_ID NOT NULL
);

ALTER TABLE RESERVATION ADD FOREIGN KEY(USER_ID) REFERENCES USER(ID);
ALTER TABLE RESERVATION ADD FOREIGN KEY(MOVIE_ID) REFERENCES MOVIE(ID);
ALTER TABLE RESERVATION ADD FOREIGN KEY(MOVIE_TIME_ID) REFERENCES MOVIE_TIME(ID);
